### ISSUE TITLE
Install issue - bin folder missing

### ISSUE THREAD

**Issue by nagasridhar** [telatin/qax#3]
I was following your install instructions to use the pre-compiled binaries. 

# From macOS
wget -O qax "https://github.com/telatin/qax/raw/main/bin/qax_mac"

However your main branch does not have the binaries placed on github.

**Comment by telatin** [comment]
Hi, I update the docs can you try with the new link?

 

 

> Pre-compiled binaries are the fastest and easiest way to get _qax_. To get the latest version,
use the following command, otherwise check the [stable releases](https://github.com/telatin/qax/releases).  


```
# From macOS
wget -O qax "https://github.com/telatin/qax/releases/download/v0.9.6/qax-macos"
chmod +x qax
```

Let me know if something goes wrong. Note this should be an x86 binary that will work with a Rosetta emulated terminal on Apple Silicon (or just as it is on Intel Macs)
